[package]
name = "gba-rust"
version = "0.1.0"
authors = ["guotong-chn <haining.cao@roam2free.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
minifb = "0.18"